version: 2.1
jobs:
  ubuntu-21-10:
    docker:
      - image: ubuntu
    steps:
      - checkout

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils shc dialog
