version: 2.1
jobs:
  ubuntu-21-10:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: ubuntu:21:10
    steps:
      - checkout

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils \
              shc dialog unzip zip lpr perl wget gfortran g++ xorg xorg-dev \
              r-base-core libcurl4-openssl-dev file tzdata

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            chmod +x /usr/local/bin/rcli
            rcli install 4.1.2
            R -q -s -e "R.version.string" > /tmp/test-results/R-version

      - store_test_results:
          path: /tmp/test-results

  ubuntu-20-04:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils \
              shc dialog unzip zip lpr perl wget gfortran g++ xorg xorg-dev \
              r-base-core libcurl4-openssl-dev file tzdata

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            chmod +x /usr/local/bin/rcli
            rcli install 4.1.2
            R -q -s -e "R.version.string" > /tmp/test-results/R-version

      - store_test_results:
          path: /tmp/test-results

  centos8:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: centos:8
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install epel-release yum-utils
            yum -y config-manager --set-enabled powertools
            yum -y install wget redhat-lsb-core sudo openblas shc R texinfo-tex openblas-devel

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli
            chmod +x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            rcli install 4.1.2
            R -q -s -e "R.version.string" > /tmp/test-results/R-version

      - store_test_results:
          path: /tmp/test-results

  centos7:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: centos:7
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install wget redhat-lsb-core sudo openblas-devel shc R

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli
            chmod +x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            rcli install 4.1.2
            R -q -s -e "R.version.string"

  fedora:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: fedora
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install wget redhat-lsb-core sudo openblas-devel shc R readline-devel \
              xorg-x11-server-devel xorg-x11-server-Xorg xorg-x11-server-common

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli
            chmod +x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            rcli install 4.1.2
            R -q -s -e "R.version.string"

workflows:
  test:
    jobs:
      - ubuntu-21-10
      - ubuntu-20-04
      - centos8
      - fedora
