version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  ubuntu-21-10:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: pats22/ubuntu-21.10-rcli
    steps:
      - checkout

      - run:
          name: Tests
          command: bash tests/ubuntu-21.10/test-ubuntu-21.10.sh

      - store_artifacts:
          path: /tmp/test-results/out.txt
          destination: artifact-file

  ubuntu-20-04:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: pats22/ubuntu-20.04-rcli
    steps:
      - checkout

      - run:
          name: Tests
          command: bash tests/ubuntu-20.04/test-ubuntu-20.04.sh

      - store_artifacts:
          path: /tmp/test-results/out.txt
          destination: artifact-file

  rockylinux8:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: pats22/rockylinux8-rcli
    steps:
      - checkout

      - run:
          name: Tests
          command: bash tests/rockylinux8/test-rockylinux8.sh

      - store_artifacts:
          path: /tmp/test-results/out.txt
          destination: artifact-file

  centos7:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: pats22/centos7-rcli
    steps:
      - checkout

      - run:
          name: Tests
          command: bash tests/centos7/test-centos7.sh

      - store_artifacts:
          path: /tmp/test-results/out.txt
          destination: artifact-file

  fedora:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: pats22/fedora-rcli
    steps:
      - checkout

      - run:
          name: Tests
          command: bash tests/fedora-latest/test-fedora.sh

      - store_artifacts:
          path: /tmp/test-results/out.txt
          destination: artifact-file

workflows:
  test:
    jobs:
      - ubuntu-20-04
          # post-steps:
          #   - codecov/upload:
          #     file: coverage/codecov-result.json
      - rockylinux8
          # post-steps:
          #   - codecov/upload:
          #     file: coverage/codecov-result.json

  # CRON job daily at 4 am in the morning
  # - runs the "build" job on the master branch and builds package cache
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ubuntu-20-04
      # - ubuntu-21-10
      - fedora
      - rockylinux8
      - centos7
