version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  ubuntu-21-10:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: ubuntu:21.10
    steps:
      - checkout

      - run:
          name: Install bundler and dependencies
          command: |
            apt update -y
            apt install -y ruby ruby-dev
            gem install bashcov

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils \
              shc dialog unzip zip lpr perl wget gfortran g++ xorg xorg-dev \
              r-base-core libcurl4-openssl-dev file tzdata

      - run:
          name: Tests
          command: bashcov tests/ubuntu-21.10/test-ubuntu-21.10.sh

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

  ubuntu-20-04:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout

      - run:
          name: Install bundler and dependencies
          command: |
            apt update -y
            apt install -y ruby ruby-dev
            gem install bashcov

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils \
              shc dialog unzip zip lpr perl wget gfortran g++ xorg xorg-dev \
              r-base-core libcurl4-openssl-dev file tzdata

      - run:
          name: Tests
          command: bashcov tests/ubuntu-20.04/test-ubuntu-20.04.sh

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

  centos8:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: centos:8
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install epel-release yum-utils
            yum -y config-manager --set-enabled powertools
            yum -y install wget redhat-lsb-core sudo openblas R texinfo-tex openblas-devel ruby ruby-devel
            gem install bashcov

      - run:
          name: Tests
          command: bashcov tests/centos8/test-centos8.sh

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

  centos7:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: centos:7
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install epel-release yum-utils
            # install ruby 2.7
            yum install -y centos-release-scl-rh
            yum install -y rh-ruby27-ruby rh-ruby27-ruby-devel
            export PATH=/opt/rh/rh-ruby27/root/usr/local/bin:/opt/rh/rh-ruby27/root/usr/bin${PATH:+:${PATH}}
            export LD_LIBRARY_PATH=/opt/rh/rh-ruby27/root/usr/local/lib64:/opt/rh/rh-ruby27/root/usr/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
            export MANPATH=/opt/rh/rh-ruby27/root/usr/local/share/man:/opt/rh/rh-ruby27/root/usr/share/man:$MANPATH
            export PKG_CONFIG_PATH=/opt/rh/rh-ruby27/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby27/root/usr/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
            export XDG_DATA_DIRS=/opt/rh/rh-ruby27/root/usr/local/share:/opt/rh/rh-ruby27/root/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}
            export PATH=/opt/rh/rh-ruby27/root/usr/local/bin:$PATH
            # install r-deps
            yum -y install wget redhat-lsb-core sudo openblas R texinfo-tex openblas-devel
            gem install bashcov

      - run:
          name: Tests
          command: bashcov tests/centos7/test-centos7.sh

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

  fedora:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: fedora
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install wget redhat-lsb-core sudo openblas-devel R readline-devel \
              xorg-x11-server-devel xorg-x11-server-Xorg xorg-x11-server-common xorg-x11-server-devel libX11-devel libXt-devel libcurl-devel ruby ruby-devel
            gem install bashcov

      - run:
          name: Tests
          command: bashcov tests/fedora-latest/test-fedora.sh

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

workflows:
  test:
    jobs:
      - ubuntu-20-04:
          post-steps:
            - codecov/upload:
              file: coverage/codecov-result.json
      - centos8:
          post-steps:
            - codecov/upload:
              file: coverage/codecov-result.json

  # CRON job daily at 4 am in the morning
  # - runs the "build" job on the master branch and builds package cache
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ubuntu-20-04
      - ubuntu-21-10
      - fedora
      - centos8
      - centos7
