version: 2.1
jobs:
  ubuntu-21-10:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: ubuntu:21.10
    steps:
      - checkout

      - run:
          name: Install bundler and dependencies
          command: apt update -y && apt install -y ruby && bundle update --bundler && bundle install
      - run:
          name: Run scripts
          command: bashcov script.sh

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils \
              shc dialog unzip zip lpr perl wget gfortran g++ xorg xorg-dev \
              r-base-core libcurl4-openssl-dev file tzdata

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            mkdir -p /tmp/test-results
            chmod +x /usr/local/bin/rcli
            rcli install 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" > /tmp/test-results/out >> /tmp/test-results/out
            if [[ $(diff tests/ubuntu-21.10/test-out.txt /tmp/test-results/out)  == "" ]] ; then exit 0; else exit 1 ; fi

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

      - run:
          name: Upload reports to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f coverage/codecov-result.json -Z

  ubuntu-20-04:
    environment:
      TZ: Europe/Zurich
      DEBIAN_FRONTEND: noninteractive
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout

      - run:
          name: Install bundler and dependencies
          command: apt update -y && apt install -y ruby && bundle update --bundler && bundle install
      - run:
          name: Run scripts
          command: bashcov script.sh

      - run:
          name: "Install apt deps"
          command: |
            apt update -y
            apt install -y curl gcc g++ lsb-release wget dpkg sudo apt-utils \
              shc dialog unzip zip lpr perl wget gfortran g++ xorg xorg-dev \
              r-base-core libcurl4-openssl-dev file tzdata

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            mkdir -p /tmp/test-results
            chmod +x /usr/local/bin/rcli
            rcli install 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" > /tmp/test-results/out
            rcli install 3.6.3 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            rcli switch 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            if [[ $(diff tests/ubuntu-20.04/test-out.txt /tmp/test-results/out)  == "" ]] ; then exit 0; else exit 1 ; fi

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

      - run:
          name: Upload reports to Codecov
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f coverage/codecov-result.json -Z

  centos8:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: centos:8
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install epel-release yum-utils
            yum -y config-manager --set-enabled powertools
            yum -y install wget redhat-lsb-core sudo openblas shc R texinfo-tex openblas-devel

      - run:
          name: "Install rcli"
          command: |
            mkdir -p /tmp/test-results
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli
            chmod +x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            rcli install 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" > /tmp/test-results/out
            rcli install 3.6.3 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            rcli switch 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            if [[ $(diff tests/centos8/test-out.txt /tmp/test-results/out)  == "" ]] ; then exit 0; else diff --unified tests/centos8/test-out.txt /tmp/test-results/out && exit 1 ; fi

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

  centos7:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: centos:7
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install epel-release yum-utils
            yum -y install wget redhat-lsb-core sudo openblas shc R texinfo-tex openblas-devel

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli
            chmod +x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            mkdir -p /tmp/test-results
            rcli install 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            rcli install 3.6.3 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            rcli switch 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" >> /tmp/test-results/out
            if [[ $(diff tests/centos7/test-out.txt /tmp/test-results/out)  == "" ]] ; then exit 0; else exit 1 ; fi

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

  fedora:
    environment:
      TZ: Europe/Zurich
    docker:
      - image: fedora
    steps:
      - checkout

      - run:
          name: "Install yum deps"
          command: |
            yum -y install wget redhat-lsb-core sudo openblas-devel shc R readline-devel \
              xorg-x11-server-devel xorg-x11-server-Xorg xorg-x11-server-common xorg-x11-server-devel libX11-devel libXt-devel libcurl-devel

      - run:
          name: "Install rcli"
          command: |
            shc -f rcli.sh && \
            mv rcli.sh.x /usr/local/bin/rcli
            chmod +x /usr/local/bin/rcli

      - run:
          name: "Install R"
          command: |
            mkdir -p /tmp/test-results
            rcli install 4.1.2 >> /tmp/test-results/out
            R -q -s -e "R.version.string" > /tmp/test-results/out >> /tmp/test-results/out
            if [[ $(diff tests/fedora/test-out.txt /tmp/test-results/out)  == "" ]] ; then exit 0; else diff --unified tests/fedora/test-out.txt /tmp/test-results/out && exit 1 ; fi

      - store_artifacts:
          path: /tmp/test-results/out
          destination: artifact-file

workflows:
  test:
    jobs:
      - ubuntu-20-04
      - centos8

  # CRON job daily at 4 am in the morning
  # - runs the "build" job on the master branch and builds package cache
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ubuntu-20-04
      - ubuntu-21-10
      - fedora
      - centos8
      - centos7
