name: Docker Build And Push To Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"


jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2
        id: git_checkout

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rockylinux8 Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/rockylinux8"
          push: true
          tags: pats22/rockylinux8-rcli:latest

      - name: Build and push Centos7 Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/centos7"
          push: true
          tags: pats22/centos7-rcli:latest

      - name: Build and push Ubuntu 20.04 Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/ubuntu20.04"
          push: true
          tags: pats22/ubuntu-20.04-rcli:latest

      - name: Build and push Ubuntu 21.10 Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/ubuntu21.10"
          push: true
          tags: pats22/ubuntu-21.10-rcli:latest

      - name: Build and push Fedora Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/fedora"
          push: true
          tags: pats22/fedora-rcli:latest
