name: Docker Build And Push To Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"


jobs:
  build:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v2
        id: git_checkout

      # - name: Set up JDK 12.0
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 12.0

      # - name: Build with Gradle
      #   run: ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rockylinux8 Image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker/rockylinux8"
          push: true
          tags: pats22/rockylinux8-rcli:latest

      # - name: Build rockylinux8 Image
      #   id: buildAndPushImage-rocky
      #   uses: abhishek-070/docker-image-build-push-action@v1.0
      #   with:
      #     registry_url: "docker.io"
      #     repository_name: "rockylinux8-rcli"
      #     user_name: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     image_version: "latest"
      #     docker_file: "docker/rockylinux8/Dockerfile"

      # - name: Build Centos7 Image
      #   id: buildAndPushImage-centos7
      #   uses: abhishek-070/docker-image-build-push-action@v1.0
      #   with:
      #     registry_url: "docker.io"
      #     repository_name: "centos7-rcli"
      #     user_name: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     image_version: "latest"
      #     docker_file: "docker/centos7/Dockerfile"

      - name: Build and push Centos7 Image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker/centos7"
          push: true
          tags: pats22/centos7-rcli:latest

      # - name: Build Ubuntu 20.04 Image
      #   id: buildAndPushImage-ubuntu-20
      #   uses: abhishek-070/docker-image-build-push-action@v1.0
      #   with:
      #     registry_url: "docker.io"
      #     repository_name: "ubuntu-20.04-rcli"
      #     user_name: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     image_version: "latest"
      #     docker_file: "docker/ubuntu20.04/Dockerfile"

      - name: Build and push Ubuntu 20.04 Image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker/ubuntu20.04"
          push: true
          tags: pats22/ubuntu-20.04-rcli:latest

      # - name: Build Ubuntu 21.10 Image
      #   id: buildAndPushImage-ubuntu-21
      #   uses: abhishek-070/docker-image-build-push-action@v1.0
      #   with:
      #     registry_url: "docker.io"
      #     repository_name: "ubuntu-21.10-rcli"
      #     user_name: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     image_version: "latest"
      #     docker_file: "docker/ubuntu21.10/Dockerfile"

      - name: Build and push Ubuntu 21.10 Image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker/ubuntu21.10"
          push: true
          tags: pats22/ubuntu-21.10-rcli:latest

      # - name: Build Fedora Image
      #   id: buildAndPushImage-fedora
      #   uses: abhishek-070/docker-image-build-push-action@v1.0
      #   with:
      #     registry_url: "docker.io"
      #     repository_name: "fedora-rcli"
      #     user_name: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     image_version: "latest"
      #     docker_file: "docker/fedora/Dockerfile"

      - name: Build and push Fedora Image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:docker/fedora"
          push: true
          tags: pats22/fedora-rcli:latest
