on:
  push:
  pull_request:

name: rcli-macOS

jobs:
  test-rcli:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Ruby dependencies
        run: bundle install
      - name: Bashcov
        run: bashcov rcli.sh

      - name: Install R
        shell: bash
        run: |
          brew install --cask r

      - name: Tests
        shell: bash
        run: |
          mkdir -p /tmp/test-results && touch /tmp/test-results/out.txt
          ./rcli.sh install 4.1.2 && R -q -s -e "R.version.string" >> /tmp/test-results/out.txt
          ./rcli.sh install 4.0.5 && R -q -s -e "R.version.string" >> /tmp/test-results/out.txt
          echo -e "#### Switching 4.0.5 -> 4.1.2"
          ./rcli.sh switch 4.1.2 >> /tmp/test-results/out.txt
          R -q -s -e "install.packages('gam', repos = 'https://cran.us.r-project.org', quiet = TRUE)" > /dev/null
          echo -e "#### Switching 4.1.2 -> 4.0.5"
          ./rcli.sh switch 4.0.5 --debug >> /tmp/test-results/out.txt
          R -q -s -e "install.packages('cli', repos = 'https://cran.us.r-project.org', quiet = TRUE)" > /dev/null
          echo -e "#### Switching 4.0.5 -> 4.1.2"
          ./rcli.sh switch 4.1.2 --debug  >> /tmp/test-results/out.txt
          R -q -s -e "library('gam')" >> /tmp/test-results/out.txt

      - name: "Upload artifacts"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/test-results/out.txt

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: coverage/codecov-result.json
          flags: unittests # optional
          name: rcli
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
