on:
  push:
  pull_request:

name: rcli-macOS

jobs:
  test-rcli:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install R
        shell: bash
        run: |
          brew install --cask r
          echo -e "Architecture: $(arch)"

      - name: Tests
        shell: bash
        run: |
          echo -e "SYSLIB: $(R -q -s -e "tail(.libPaths())" | cut -c 6- | sed 's/.$//')"
          mkdir -p /tmp/test-results && touch /tmp/test-results/out
          ./rcli.sh install 4.1.2 && R -q -s -e "R.version.string" >> /tmp/test-results/out
          ./rcli.sh install 4.0.5 && R -q -s -e "R.version.string" >> /tmp/test-results/out
          echo -e "#### Switching 4.0.5 -> 4.1.2"
          ./rcli.sh switch 4.1.2 >> /tmp/test-results/out
          R -q -s -e "install.packages('brew')"
          ./rcli.sh switch 4.0.5 >> /tmp/test-results/out
          R -q -s -e "install.packages('magrittr')"
          ./rcli.sh switch 4.1.2  >> /tmp/test-results/out
          R -q -s -e "library('brew')"

      - name: "Upload artifacts"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/test-results/out
