on:
  push:
  pull_request:

name: rcli-macOS

jobs:
  test-rcli:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Ruby dependencies
        run: bundle update --bundler && bundle install
      - name: Run script
        run: bashcov rcli.sh

      - name: Install R
        shell: bash
        run: |
          brew install --cask r
          echo -e "Architecture: $(arch)"

      - name: Tests
        shell: bash
        run: |
          echo -e "SYSLIB: $(R -q -s -e "tail(.libPaths())" | cut -c 6- | sed 's/.$//')"
          mkdir -p /tmp/test-results && touch /tmp/test-results/out
          ./rcli.sh install 4.1.2 && R -q -s -e "R.version.string" >> /tmp/test-results/out
          ./rcli.sh install 4.0.5 && R -q -s -e "R.version.string" >> /tmp/test-results/out
          echo -e "#### Switching 4.0.5 -> 4.1.2"
          ./rcli.sh switch 4.1.2 >> /tmp/test-results/out
          R -q -s -e "install.packages('brew')"
          ./rcli.sh switch 4.0.5 >> /tmp/test-results/out
          R -q -s -e "install.packages('magrittr')"
          ./rcli.sh switch 4.1.2  >> /tmp/test-results/out
          R -q -s -e "library('brew')"

      - name: "Upload artifacts"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: /tmp/test-results/out

      - name: Upload reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f coverage/codecov-result.json -Z
